package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

    // query inferred from method name, code generated by Spring Framework
    Employee findByFirstName(String firstName);

    // JPQL query  (validity check on application init)
    @Query("from Employee e where e.firstName = :name or e.lastName = :name")
    Employee findByNameJpql(@Param("name") String name);

    //    // JPQL query with join
    @Query("select e from Employee e join e.payrolls payrolls where e.firstName = :name or e.lastName = :name")
    Employee findByNameWithIdJpql(@Param("name") String name);

    // Native SQL query  (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from employee as e where e.first_name = :name or e.last_name = :name", nativeQuery = true)
    Employee findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Employee e set e.firstName = :newName where e.firstName = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);


}
