package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface PayrollRepository extends JpaRepository<Payroll, Long>{

    // query inferred from method name, code generated by Spring Framework
    Payroll findById(long id);

    // JPQL query  (validity check on application init)
    @Query("from Payroll p where p.id = :id")
    Payroll findByIdJpql(@Param("id") long id);
    
    // Native SQL query  (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from payroll as p where p.id = :id", nativeQuery = true)
    Payroll findByIdSql(@Param("id") long id);

    @Modifying
    @Query("update Payroll p set p.payRate = :newPayRate where p.id = :id")
    void updateName(@Param("id") long id, @Param("newPayRate") double payRate);
    

}

