package csc366.jpademo;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.repository.query.Param;

// This class will be automatically implemented by Spring and made available as a "Bean" named personRepository
@Repository
public interface PersonRepository extends JpaRepository<Person, Long>{

    // query inferred from method name, code generated by Spring Framework
    Person findByFirstName(String firstName);

    // JPQL query  (validity check on application init)
    @Query("from Person p where p.firstName = :name or p.lastName = :name")
    Person findByNameJpql(@Param("name") String name);

    // JPQL query with join
    @Query("select p from Person p join p.addresses addr where p.firstName = :name or p.lastName = :name")
    Person findByNameWithAddressJpql(@Param("name") String name);
    
    // Native SQL query  (validity not checked, invalid SQL will cause runtime exception)
    @Query(value = "select * from person as p where p.first_name = :name or p.last_name = :name", nativeQuery = true)
    Person findByNameSql(@Param("name") String name);

    @Modifying
    @Query("update Person p set p.firstName = :newName where p.firstName = :oldName")
    void updateName(@Param("oldName") String oldName, @Param("newName") String newName);
    

}

